name: AParkour
version: ${project.version}
authors:
    - DavidML16
    - xiaoxing365
main: me.davidml16.aparkour.Main
softdepend: [HolographicDisplays, ProtocolLib, PlaceholderAPI, Vault, Multiverse-Core]
commands:
    aparkour:
        description: Use this to see all commands.
        aliases: [apk,pk]